### PR TITLE
Show error information

### LINKED ISSUE #170: Handle torrent error state
When a torrent enters the error state, the taskbar icon should change its progress color to indicate this.

We also need a way of presenting the error to the user. Need suggestions here :smile: The easy way would be to have the status set to `Error: <message>` but for non-trivial errors it could be quite a long message.

The `Resume` items in the context menu needs to clear the error before resuming.

Extends #168

### PR DESCRIPTION
**Pull request by vktr**
This adds a description to the torrent state showing the error message, and also adds a red error overlay to the taskbar icon.

Closes #170

### CODE REVIEW

File: src/client/ui/main_window.cpp [hunk 1]
```diff
@@ -502,12 +507,12 @@ LRESULT main_window::wnd_proc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam
...
             if (active_wanted - active_done > 0)
             {
-                taskbar_->set_progress_state(TBPF_NORMAL);
+                taskbar_->set_progress_state(has_error ? TBPF_ERROR : TBPF_NORMAL);
                 taskbar_->set_progress_value(active_done, active_wanted);
             }
             else if (paused_wanted - paused_done > 0)
             {
-                taskbar_->set_progress_state(TBPF_PAUSED);
+                taskbar_->set_progress_state(has_error ? TBPF_ERROR : TBPF_NORMAL);
```
Comment (zp) [inline src/client/ui/main_window.cpp]: Changed the `TBPF_PAUSED` to `TBPF_NORMAL`, I assume it's copy-paste mistake.

Comment (vktr) [inline src/client/ui/main_window.cpp]: Oh, good catch :smile:
